### ISSUE TITLE
add clusters

### ISSUE THREAD

**Issue by cmcnamara87** [genome-one/monarch#19]
rough idea how to do it, using what we got

disease A and disease B
get all their phenotypes
stick them together in a set (so no duplicates)

for the first item in the set
compare it, to the set (minus that item) using the owlsim api call
get the results, calculate the sim scores
if there are any over 85%, those can go in a cluster together

do it for the rest of the items in the set
if you get matches, if any of the matched terms already exist in an existing cluster, just add those new matched terms, to the existing cluster

so, its probably about 21 api calls for skeletal abnormalities for achondroplasia example
and, it might result in just in 1 big cluster, if everything in skeletal abnormalities is only like, 85% sim score away from anything else lol, but we can tweak that numbers until something shows up

for naming a cluster, you could use the LCS with the lowest information content that was used when making the cluster

**Comment by jmcmurry** [comment]
related to https://github.com/monarch-initiative/owlsim-v3/issues/89
